/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class Ctrl039_Skill_Selector_V2_Component {
    @RemoteAction
    global static List<FSL.Ctrl039_Skill_Selector_V2_Component.SkillOption> saveSkills(String skillOptionString, String stdObjName, String skillObjName, String junctionObjName, Id myId, String relationshipField) {
        return null;
    }
global class SkillJunctionObj {
}
global class SkillOption {
}
}
