/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class Ctrl001GroupOnRuleAndObjectives {
    global static String ObjectId {
        get;
        set;
    }
    global static String ObjectName {
        get;
        set;
    }
    global static String strCurrentObject {
        get;
        set;
    }
    @RemoteAction
    global static List<FSL.Ctrl001GroupOnRuleAndObjectives.FieldsLabelName> GetObjectFields(String ObjName) {
        return null;
    }
    @RemoteAction
    global static void SaveFieldsNamesOnWorkRule(Id objid, String ObjName, String ObjectFieldName, String ResourceFieldName) {

    }
global class FieldsLabelName {
}
}
