/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class Ctrl739_ComplexWork {
    @RemoteAction
    global static Map<String,List<Object>> addTimeDependency(Id serviceAppId, Id sa1, Id sa2, String dependency, Boolean sameResource) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getFslOperation(Long schedulingStartLong, Id opId) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<Object>> getMstChain(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<ServiceAppointment>> getRelatedServices(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getServiceListFields() {
        return null;
    }
    @RemoteAction
    global static List<FSL.TimeDependencyUtils.SAWithLevel> getTree(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<Object>> removeTimeDependency(Id serviceAppId, Id timeDep) {
        return null;
    }
    @RemoteAction
    global static List<FSL.ScheduleResult> scheduleService2(Id service) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> scheduleService(Id service) {
        return null;
    }
}
