/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class ctrl079_ResourceCalendar {
    @RemoteAction
    global static List<FSL__Dictionaries__c> getDictionaries() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getNAFieldset() {
        return null;
    }
    @RemoteAction
    global static List<ResourceAbsence> getNAs(String strStartDate, String strFinishDate, Id resourceId) {
        return null;
    }
    @RemoteAction
    global static List<RecordType> getNaRecordTypes() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getNaTooltipFieldset() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getServiceFieldset() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getServiceTooltipFieldset() {
        return null;
    }
    @RemoteAction
    global static List<ServiceAppointment> getServices(String strStartDate, String strFinishDate, Id resourceId) {
        return null;
    }
    @RemoteAction
    global static List<String> getStatuses() {
        return null;
    }
    @RemoteAction
    global static Map<String,String> getTranslations(String objectName, String fieldName) {
        return null;
    }
    @RemoteAction
    global static Map<String,Double> getduartionPerDay(String strStartDate, String strFinishDate, Id resourceId) {
        return null;
    }
}
