/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class EmergencyWizardController implements FSL.IChatterAction {
    @RemoteAction
    global static Map<String,List<Object>> getBreadcrumbs2(List<Id> resources) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<SObject>> getBreadcrumbs(List<Id> resources) {
        return null;
    }
    @RemoteAction
    global static List<FSL__Scheduling_Policy__c> getPolicies() {
        return null;
    }
}
