/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class GlobalAPIS {
    global GlobalAPIS() {

    }
    global static List<FSL.StatusTransition> GetAllStatusTransitions() {
        return null;
    }
    global static List<FSL__Service_Legal_Statuses__c> GetStatusTransitions() {
        return null;
    }
    global static void addStatusTransition(String fromStatus, String toStatus) {

    }
}
