/*
系统会生成此文件，且不是此托管全局类的
实际源代码。
此只读文件显示显示类的全局构造器、
方法、变量和属性。
要启动代码编译，所有方法会返回空。
*/
global class OAAS {
    global OAAS() {

    }
    global Id Optimize(FSL.OAASRequest Request) {
        return null;
    }
    global Id Reshuffle(Id serviceId, Id policyId) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, String candidateSasFields, String unschedulableServicesField, Decimal maxOptRuntime) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, String candidateSasFields, String unschedulableServicesField, Decimal maxOptRuntime, Datetime nowTimeOnSchedule) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, Set<Id> candidateSas, Set<Id> unschedulableServices, Decimal maxOptRuntime) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, Set<Id> candidateSas, Set<Id> unschedulableServices, Decimal maxOptRuntime, Datetime nowTimeOnSchedule) {
        return null;
    }
}
